# Generated by Django 3.2.9 on 2022-01-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(blank=True, default='feedback.jpg', upload_to='Feedback/'),
        ),
    ]
