# Generated by Django 3.2 on 2021-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTitleAndExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='homeimages')),
                ('group_link', models.URLField(blank=True, max_length=999, null=True)),
                ('you_get', models.CharField(blank=True, max_length=255, null=True)),
                ('we_complete', models.CharField(blank=True, max_length=255, null=True)),
                ('client_review', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_quotes', models.TextField(blank=True, max_length=999, null=True)),
                ('footer_contacttitle', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('footer_linkstitle', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_paymenttitle', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_facebook_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_instagram_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_twitter_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_linkedin_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_youtube_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_copyright', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
