# Generated by Django 3.2 on 2021-06-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepagetitleandextra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagetitleandextra',
            old_name='client_review',
            new_name='client_review_title',
        ),
        migrations.RenameField(
            model_name='homepagetitleandextra',
            old_name='footer_contacttitle',
            new_name='footer_contact_title',
        ),
        migrations.RenameField(
            model_name='homepagetitleandextra',
            old_name='footer_linkstitle',
            new_name='footer_links_title',
        ),
        migrations.RenameField(
            model_name='homepagetitleandextra',
            old_name='footer_paymenttitle',
            new_name='footer_payment_title',
        ),
        migrations.RenameField(
            model_name='homepagetitleandextra',
            old_name='we_complete',
            new_name='we_complete_title',
        ),
        migrations.RenameField(
            model_name='homepagetitleandextra',
            old_name='you_get',
            new_name='you_get_title',
        ),
    ]
