# Generated by Django 3.2 on 2021-06-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210620_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageWeComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
