# Generated by Django 3.2 on 2021-06-21 03:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepagewecomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagewecomplete',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
