# Generated by Django 3.2 on 2021-06-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepagewecomplete_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagetopslider',
            options={'ordering': ['img']},
        ),
        migrations.AddField(
            model_name='footer',
            name='payment_logo',
            field=models.FileField(blank=True, null=True, upload_to='homeimages'),
        ),
    ]
