# Generated by Django 3.2 on 2021-06-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210622_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='teammember')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('describe', models.TextField(blank=True, max_length=999, null=True)),
                ('short_info', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=999, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=999, null=True)),
                ('whatsapp_link', models.URLField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='ourworks')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ourworkssection')),
            ],
        ),
    ]
