# Generated by Django 3.2 on 2021-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ourworks_ourworkssection_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourworks',
            name='link',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
