# Generated by Django 3.2.7 on 2022-01-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aboutus_client_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetitleandextra',
            name='happy_client',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homepagetitleandextra',
            name='partners',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homepagetitleandextra',
            name='project_done',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homepagewecomplete',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
