# Generated by Django 3.2.9 on 2021-12-13 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_doller', models.CharField(blank=True, max_length=100, null=True)),
                ('amonut_tk', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_space', models.BooleanField(blank=True, default=True, help_text='50GB disk space', null=True)),
                ('email_account', models.BooleanField(blank=True, default=True, help_text='50 Email Account', null=True)),
                ('bandwith', models.BooleanField(blank=True, default=True, help_text='50GB disk spacet', null=True)),
                ('maintenance', models.BooleanField(blank=True, default=True, null=True)),
                ('subdomain', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
