# Generated by Django 3.2.9 on 2022-01-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='amonut_tk',
        ),
        migrations.RemoveField(
            model_name='service',
            name='amount_doller',
        ),
        migrations.RemoveField(
            model_name='service',
            name='bandwith',
        ),
        migrations.RemoveField(
            model_name='service',
            name='disk_space',
        ),
        migrations.RemoveField(
            model_name='service',
            name='email_account',
        ),
        migrations.RemoveField(
            model_name='service',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='service',
            name='subdomain',
        ),
    ]
