# Generated by Django 3.2.9 on 2022-01-02 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('second_app', '0002_auto_20220102_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceServie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('amount_doller', models.CharField(blank=True, max_length=100, null=True)),
                ('amonut_tk', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_space', models.BooleanField(blank=True, default=True, help_text='50GB disk space', null=True)),
                ('email_account', models.BooleanField(blank=True, default=True, help_text='50 Email Account', null=True)),
                ('bandwith', models.BooleanField(blank=True, default=True, help_text='50GB disk spacet', null=True)),
                ('maintenance', models.BooleanField(blank=True, default=True, null=True)),
                ('subdomain', models.BooleanField(blank=True, default=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second_app.service')),
            ],
        ),
    ]
