# Generated by Django 3.2.9 on 2022-01-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_auto_20220102_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=214)),
                ('short_desc', models.CharField(max_length=221)),
                ('img', models.ImageField(upload_to='ourworks')),
            ],
        ),
    ]
