# Generated by Django 3.2.9 on 2022-01-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0005_ourwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourwork',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='ourwork',
            name='img',
        ),
        migrations.RemoveField(
            model_name='ourwork',
            name='short_desc',
        ),
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=214)),
                ('short_desc', models.CharField(max_length=221)),
                ('img', models.ImageField(upload_to='ourworks')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second_app.ourwork')),
            ],
        ),
    ]
