# Generated by Django 3.2.9 on 2022-01-03 16:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0010_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.IntegerField()),
                ('project_done', models.IntegerField()),
                ('happy_client', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageTopSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='homeimages')),
            ],
            options={
                'ordering': ['img'],
            },
        ),
        migrations.CreateModel(
            name='HomePageWeComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageYouGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
