# Generated by Django 3.2.9 on 2022-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0011_achievement_homepagetopslider_homepagewecomplete_homepageyouget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetopslider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='homeimages'),
        ),
    ]
