# Generated by Django 3.2.9 on 2022-01-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0012_alter_homepagetopslider_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_quotes', models.TextField(blank=True, max_length=999, null=True)),
                ('footer_contact_title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('footer_links_title', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_payment_title', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_logo', models.FileField(blank=True, null=True, upload_to='homeimages')),
                ('footer_facebook_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_instagram_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_twitter_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_linkedin_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_youtube_link', models.URLField(blank=True, max_length=999, null=True)),
                ('footer_copyright', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
