# Generated by Django 3.2.9 on 2022-01-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0015_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
