# Generated by Django 3.2.9 on 2022-01-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0017_auto_20220105_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
