# Generated by Django 3.2.9 on 2022-01-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0020_auto_20220105_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
