# Generated by Django 3.2.9 on 2022-01-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0021_alter_profile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_demo_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.basicproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.proproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='standerd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.standerdproduct'),
        ),
    ]
