# Generated by Django 3.2.9 on 2022-01-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0024_items_package_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='demo',
            field=models.URLField(default=None),
        ),
    ]
