# Generated by Django 3.2.7 on 2022-01-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0028_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourwork',
            name='demo',
            field=models.URLField(blank=True, default='https://jstutul.xyz'),
        ),
        migrations.AddField(
            model_name='ourwork',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='ourwork',
            name='image',
            field=models.ImageField(default='ourwork.jpg', upload_to='Our Work/'),
        ),
    ]
